blank_issues_enabled: false
contact_links:
  - name: ThitNueaHub Support
    url: https://github.com/ARTHITSIANGWAN/Thitnueahub-Admin/discussions
    about: สอบถามข้อมูลเพิ่มเติมเกี่ยวกับระบบขุนพล
    
