package main

import (
	"fmt"
	"os"
)

type Agent struct {
	Level, Name, Role string
}

func main() {
	agents := []Agent{
		{"L1", "ทิศเหนือ", "COMMANDER"}, {"L2", "แก้วตา", "SCRIBE"}, {"L3", "น้ำอิง", "ARTIST"},
		{"L4", "พลายทอง", "ANALYST"}, {"L5", "ไอ้จ๊อด", "AUDITOR"}, {"L6", "Merchant", "MERCHANT"},
		{"L7", "พลายแก้ว", "ORACLE"}, {"L8", "Glock", "GUARDIAN"}, {"L9", "Sentinel", "SENTINEL"},
		{"L10", "Auditor", "AUDITOR"}, {"L11", "Balancer", "BALANCER"},
	}

	for _, a := range agents {
		dir := fmt.Sprintf("docs/series/11-lipos/%s_%s/assets", a.Level, a.Name)
		os.MkdirAll(dir, 0755)

		content := fmt.Sprintf(`# 🐯 EVOLUTION: %s (%s)
**Role:** %s | **Base:** Jarvis V83

## 🛰️ Visual Progress Log
| Stage | Asset Link (WebP/MP4) | Status |
| :--- | :--- | :--- |
| **Birth** | | ⚪ |
| **Growth** | | ⚪ |
| **Mastery** | | ⚪ |

## 🎥 Episode Tracker (16 EP)
- [ ] 1-4 | [ ] 5-8 | [ ] 9-12 | [ ] 13-16

---
*Generated by ThitNueaHub Admin V83 Engine*
`, a.Name, a.Level, a.Role)

		os.WriteFile(fmt.Sprintf("docs/series/11-lipos/%s_%s/evolution.md", a.Level, a.Name), []byte(content), 0644)
	}
	fmt.Println("🚀 11 Lipos Evolution Series Setup Complete!")
}
